import type { Config } from 'tailwindcss';

/**
 * Phase 110 sets up Tailwind and the dark-mode strategy only. The design
 * tokens -- colour, type scale, spacing -- arrive in Phase 111 (T111.1), where
 * they are matched to the matplotlib figure palette so a chart drawn in the
 * browser and a 300 dpi PNG generated by Python do not disagree about what
 * "the first series" looks like.
 *
 * `darkMode: 'class'` rather than 'media', because next-themes toggles a class
 * on <html> and needs Tailwind to follow it rather than the OS setting.
 */
const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: { extend: {} },
  plugins: [],
};

export default config;
