import { manifest } from '@/lib/generated';

/**
 * The run manifest, in the footer, on every page (T110.4 / T109.4).
 *
 * This is the provenance of everything above it: which commit produced the
 * numbers on screen, when they were exported, and how many artifacts were
 * read. A dashboard whose numbers cannot be traced to a run is the failure this
 * project exists to avoid, so the trace is visible rather than buried in a JSON
 * file nobody opens.
 *
 * Nothing here is formatted in the browser. `exported_utc` is rendered as the
 * ISO string Python emitted, not reformatted client-side, and the counts are
 * integers straight from the manifest.
 */
export function Footer() {
  const excluded = manifest.excluded_dirs ?? [];
  const commit = manifest.git_commit ? manifest.git_commit.slice(0, 12) : 'unknown';

  return (
    <footer className="mt-16 border-t border-slate-200 bg-slate-50 px-4 py-8 text-xs leading-relaxed text-slate-600 dark:border-slate-800 dark:bg-slate-900/40 dark:text-slate-400">
      <div className="mx-auto grid max-w-7xl gap-6 sm:grid-cols-2 lg:grid-cols-4">
        <div>
          <p className="font-semibold text-slate-800 dark:text-slate-200">
            {manifest.framework}
          </p>
          <p className="mt-1">
            PCG heart-sound classification. Academic screening and decision-support
            prototype.
          </p>
        </div>

        <div>
          <p className="font-semibold text-slate-800 dark:text-slate-200">Provenance</p>
          <dl className="mt-1 space-y-0.5">
            <div className="flex gap-2">
              <dt className="text-slate-500">commit</dt>
              <dd className="font-mono">{commit}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-slate-500">branch</dt>
              <dd className="font-mono">{manifest.git_branch ?? 'unknown'}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-slate-500">run</dt>
              <dd className="font-mono">{manifest.run_id || 'unrecorded'}</dd>
            </div>
          </dl>
        </div>

        <div>
          <p className="font-semibold text-slate-800 dark:text-slate-200">Build-time export</p>
          <dl className="mt-1 space-y-0.5">
            <div className="flex gap-2">
              <dt className="text-slate-500">exported</dt>
              <dd className="font-mono">{manifest.exported_utc}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-slate-500">tables</dt>
              <dd className="font-mono">{manifest.n_tables}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-slate-500">figures</dt>
              <dd className="font-mono">{manifest.n_figures}</dd>
            </div>
            <div className="flex gap-2">
              <dt className="text-slate-500">sources</dt>
              <dd className="font-mono">{manifest.sources.length}</dd>
            </div>
          </dl>
        </div>

        <div>
          <p className="font-semibold text-slate-800 dark:text-slate-200">
            Not exported in this build
          </p>
          {excluded.length === 0 ? (
            <p className="mt-1">Every source directory was read.</p>
          ) : (
            <ul className="mt-1 space-y-1">
              {excluded.map((entry) => (
                <li key={entry.dir}>
                  <span className="font-mono">{entry.dir}</span> — {entry.reason}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>

      <p className="mx-auto mt-6 max-w-7xl text-slate-500 dark:text-slate-500">
        Every precomputed value on this site is generated by
        <span className="font-mono"> scripts/17_export_frontend_data.py</span> and imported
        from <span className="font-mono">lib/generated/</span>. The browser neither computes
        nor rounds a reported value. Only live inference crosses the wire at runtime.
      </p>
    </footer>
  );
}
