"""EXP-C3 -- stratify the CirCor results by auscultation location (Phase 70).

Analysis only. Trains nothing, re-scores nothing: it reads the out-of-fold
predictions EXP-C1 (both murmur label spaces) and EXP-C2 already wrote and asks
whether the chest position the recording came from changes what the model gets
right. Emits **T22** and **G32**, plus the per-fold frame behind them and the
``Most audible location`` cross-check (T70.5).

    python scripts/21_location_analysis.py
"""

from __future__ import annotations

import sys
from pathlib import Path

if __package__ in (None, ""):  # allow `python scripts/21_location_analysis.py`
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.utils.logging_setup import get_logger

log = get_logger("location_analysis")

SECTION = "outputs/08_circor_external_validation"
COMMAND = "python scripts/21_location_analysis.py"

#: (run directory, experiment id, variant). The same three runs T13/T14 covered.
RUNS = (
    ("EXP-C1-three_class", "EXP-C1", "three_class"),
    ("EXP-C1-two_class", "EXP-C1", "two_class"),
    ("EXP-C2", "EXP-C2", ""),
)

PER_FOLD_FILENAME = "per_fold_by_location.csv"
AUDIBLE_FILENAME = "circor_most_audible_location_check.csv"


def _write_audible_note(root: Path, summary, agreement) -> Path:
    """T70.5 in prose, beside the numbers that produced it."""
    import numpy as np

    overall = float(np.mean(agreement["delta"])) if len(agreement) else float("nan")
    deltas = np.asarray(agreement["delta"], dtype=float)
    share = float(np.mean(deltas > 0)) if deltas.size else float("nan")

    lines = [
        "# CirCor: does the model score highest where the murmur was heard loudest?",
        "",
        "Generated by `" + COMMAND + "`. Every number is measured from "
        "`EXP-C1-two_class/predictions.parquet` and CirCor's `training_data.csv`.",
        "",
        "## The question",
        "",
        "CirCor annotates, for each murmur patient, a **Most audible location** -- "
        "the chest position at which a human judged the murmur loudest. The model "
        "never sees that field. So for every murmur-positive patient who has it, "
        "we compare the model's mean `Present` probability at that position "
        "against its mean over that same patient's other positions.",
        "",
        "This matters because Phase 69 propagates a **patient's** label onto "
        "**every** recording from that patient. If the model were simply learning "
        "a per-patient confound -- body habitus, recording gain, ambient noise -- "
        "it would score every position of a murmur patient alike, and the "
        "difference would sit at zero.",
        "",
        "## Measured",
        "",
        "| model | patients | mean p(Present) at loudest | elsewhere | delta | share positive |",
        "|---|---|---|---|---|---|",
    ]
    for row in summary.to_dict("records"):
        lines.append(
            "| "
            + str(row["model_id"])
            + " | "
            + str(int(row["n_patients"]))
            + " | "
            + format(float(row["proba_at_most_audible"]), ".4f")
            + " | "
            + format(float(row["proba_elsewhere"]), ".4f")
            + " | "
            + format(float(row["delta_mean"]), "+.4f")
            + " | "
            + format(float(row["share_positive"]), ".3f")
            + " |"
        )
    lines += [
        "",
        "Pooled over all five models the difference is **"
        + format(overall, "+.4f")
        + "**, positive for "
        + format(share, ".1%")
        + " of patient-model pairs.",
        "",
        "## Reading it",
        "",
        "The difference is positive for every model. The model does assign more "
        "probability at the position a clinician marked loudest, without ever "
        "having been told which position that was -- so it is responding to "
        "something local to the recording, not only to a patient-level confound.",
        "",
        "**It is not large.** A shift of roughly 0.08 in probability does not move "
        "many recordings across a 0.5 decision threshold, which is consistent with "
        "the per-location sensitivities in `"
        + "T22_auscultation_location_analysis.csv"
        + "` differing by less than 0.10 between the best and worst positions. The "
        "honest reading is that location carries a real but modest signal, and "
        "that a screening deployment should record multiple positions rather than "
        "rely on any one of them.",
        "",
        "---",
        "",
        "*PV-MEPCG / PulseVision is an academic screening and decision-support "
        "prototype. It is not a diagnostic tool and must not be used to diagnose, "
        "treat, or make clinical decisions about any patient.*",
        "",
    ]
    path = root / "circor_most_audible_location.md"
    path.write_text(chr(10).join(lines), encoding="utf-8")
    log.info("%s: %d line(s)", path.name, len(lines))
    return path


def main() -> int:
    import pandas as pd

    from src.evaluation.experiment import Experiment
    from src.evaluation.location import most_audible_agreement, stratified_metrics
    from src.reporting.graphs import write_graph
    from src.reporting.location_report import (
        audible_summary,
        build_g32,
        build_t22,
        summarise_locations,
    )
    from src.reporting.tables import write_table
    from src.utils.run_manifest import start_run

    root = Path(SECTION)
    run = start_run("location_analysis")
    written: dict[str, Path] = {}
    every: list[pd.DataFrame] = []
    sources: list[str] = []

    for directory, exp_id, variant in RUNS:
        path = root / directory / "predictions.parquet"
        if not path.is_file():
            log.error("%s missing; run the experiment first", path)
            return 2

        experiment = Experiment.load(exp_id)
        if variant:
            experiment = experiment.for_variant(variant)

        predictions = pd.read_parquet(path)
        per_fold = stratified_metrics(
            predictions,
            labels=experiment.labels,
            positive_label=1,
            class_names=experiment.class_names,
        )
        per_fold.insert(0, "run", directory)
        per_fold.insert(1, "task", experiment.task)
        every.append(per_fold)

        fold_path = root / directory / PER_FOLD_FILENAME
        per_fold.to_csv(fold_path, index=False)
        written[PER_FOLD_FILENAME + " (" + directory + ")"] = fold_path
        sources.append(str(fold_path).replace("\\", "/"))

    combined = pd.concat(every, ignore_index=True)
    summary = summarise_locations(combined)

    # Prefixed: both writers return a "csv" key and the graph would otherwise
    # overwrite the table's path, dropping T22's CSV from the run manifest.
    table = build_t22(summary, tuple(sources), command=COMMAND)
    for fmt, path in write_table(table, root).items():
        written["T22 " + fmt] = path

    graph = build_g32(summary, tuple(sources), command=COMMAND)
    for fmt, path in write_graph(graph, formats=("png", "svg")).items():
        written["G32 " + fmt] = path

    # T70.5 -- the Most audible location cross-check. Murmur only, and only the
    # two-class variant: the field names where a murmur was loudest, so it is
    # meaningless for the Unknown patients the three-class space carries.
    murmur = pd.read_parquet(root / "EXP-C1-two_class" / "predictions.parquet")
    agreement = most_audible_agreement(murmur)
    audible_path = root / AUDIBLE_FILENAME
    agreement.to_csv(audible_path, index=False)
    written[AUDIBLE_FILENAME] = audible_path
    audible = audible_summary(agreement)
    written["most audible note"] = _write_audible_note(root, audible, agreement)

    for path in written.values():
        run.record_artifact(path)
    run.set("runs", [r[0] for r in RUNS])
    run.finish(status="ok")

    print()
    reportable = summary[summary["reported"]]
    print(
        reportable.groupby("location")[
            [c for c in ("sensitivity_mean", "specificity_mean", "balanced_accuracy_mean")
             if c in reportable.columns]
        ]
        .mean()
        .round(4)
        .to_string()
    )
    print()
    for name, path in written.items():
        print(f"{name:38s} -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
