"""Feature-family figures: FE-07 (Phase 35), FE-08 (Phase 36), FE-09 (Phase 37).

**The record is chosen by rule, not by eye.** These figures reuse
:func:`src.preprocessing.figures.select_records`, which resolves "a
representative normal PhysioNet recording" to the labelled, non-duplicate,
non-low-quality D1 record whose duration is closest to its class median, with
``record_uid`` breaking ties. A figure captioned "representative" that was
actually picked because it looked good is a quiet form of cherry-picking and
cannot be regenerated by anyone checking the work.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

__all__ = [
    "FE_FIGURES",
    "G10_FILENAME",
    "features_dir",
    "diagrams_dir",
    "plot_mfcc_heatmap",
    "plot_family_counts",
    "plot_chroma_heatmap",
    "plot_wavelet_decomposition",
    "plot_signal_envelope",
    "generate_all",
]

#: G10 lives in ``outputs/13_figures_diagrams`` -- its permanent home per the
#: section-17 tree and Phase 91 -- not beside the FE artifacts. Emitting it
#: twice under two paths would give the evidence index two rows claiming to be
#: the same figure.
G10_FILENAME = "feature_family_count_chart.png"

FE_FIGURES: dict[str, str] = {
    "FE-06": "mfcc_heatmap.png",
    "FE-07": "chroma_heatmap.png",
    "FE-08": "wavelet_decomposition.png",
    "FE-09": "signal_envelope.png",
}


def features_dir(out_dir: str | Path | None = None) -> Path:
    from src.utils.config import load_config
    from src.utils.io import ensure_dir

    if out_dir is not None:
        return ensure_dir(out_dir)
    return ensure_dir(load_config("paths").require("outputs.features"))


def _representative() -> Any:
    from src.preprocessing.figures import select_records

    return select_records()["normal"]


def _preprocessed(record: Any) -> tuple[np.ndarray, int]:
    from src.preprocessing.pipeline import preprocess
    from src.utils.config import load_config

    root = Path(load_config("paths").require("project_root"))
    result = preprocess(root / str(record["file_path"]), record_uid=str(record["record_uid"]))
    return np.asarray(result.signal, dtype=np.float64), int(result.fs)


def plot_chroma_heatmap(
    path: str | Path, record: Any | None = None
) -> Path:
    """FE-07 -- the 12 chroma bins over time for one representative record (T35.6).

    The caption carries the T35.4 caveat, because a chroma heatmap of a heart
    sound invites exactly the musical reading the family does not support.
    """
    from src.feature_extraction.chroma import ChromaExtractor, chroma_matrix
    from src.reporting.plot_style import figure, save_figure

    if record is None:
        record = _representative()

    signal, fs = _preprocessed(record)
    settings = ChromaExtractor().settings()
    chroma = chroma_matrix(signal, fs, settings)
    if chroma.shape[1] == 0:
        raise ValueError(
            "chroma is empty for " + str(record["record_uid"]) + "; cannot draw FE-07"
        )

    duration = signal.size / fs
    low = float(chroma.min())
    high = float(chroma.max())

    # The colour scale spans the data, not a nominal 0-1. `chroma_stft`
    # normalizes every frame by its maximum, and a PCG spreads energy almost
    # evenly across the twelve pitch classes, so the real range on this corpus is
    # roughly 0.5-1.0. Forcing vmin=0 produced a uniformly bright rectangle:
    # arithmetically correct and completely unreadable. The caption states the
    # true range so the narrow dynamic range stays visible rather than being
    # hidden by the stretch -- that flatness is itself the T35.4 point.
    fig, axis = figure("double")
    image = axis.imshow(
        chroma,
        aspect="auto",
        origin="lower",
        cmap="magma",
        vmin=low,
        vmax=high,
        extent=(0.0, duration, 0.5, settings.n_chroma + 0.5),
    )
    axis.set_yticks(range(1, settings.n_chroma + 1))
    axis.set_xlabel("Time (s)")
    axis.set_ylabel("Chroma bin")
    axis.set_title(
        "Chroma representation, "
        + str(record["record_uid"])
        + " ("
        + str(settings.n_chroma)
        + " bins, "
        + str(int(settings.fmin))
        + "-"
        + str(int(settings.fmax))
        + " Hz)"
    )
    bar = fig.colorbar(image, ax=axis)
    bar.set_label("Normalized chroma energy")
    fig.tight_layout()

    return save_figure(
        fig,
        path,
        source=(
            "FE-07 | "
            + str(record["record_uid"])
            + " | range "
            + format(low, ".3f")
            + "-"
            + format(high, ".3f")
            + " | chroma is a musical-pitch construct with no physiological meaning "
            "for heart sounds; used here only as a generic harmonic-distribution "
            "descriptor (T35.4)"
        ),
    )


def plot_wavelet_decomposition(path: str | Path, record: Any | None = None) -> Path:
    """FE-08 -- the six db4 sub-bands of one representative record (T36.6).

    Each panel is annotated with the band it actually covers, because "cD1" says
    nothing on its own and the dyadic split does not line up with the 20-400 Hz
    passband. The y-axes are independent: sub-band amplitudes span three orders
    of magnitude here, and a shared scale would draw four of the six as flat
    lines.
    """
    from src.feature_extraction.wavelet import SUBBANDS, WaveletExtractor, decompose
    from src.reporting.plot_style import figure, save_figure

    if record is None:
        record = _representative()

    signal, fs = _preprocessed(record)
    settings = WaveletExtractor().settings()
    bands = decompose(signal, settings)
    if not bands:
        raise ValueError(
            "no DWT sub-bands for " + str(record["record_uid"]) + "; cannot draw FE-08"
        )

    present = [name for name in SUBBANDS if name in bands]
    fig, axes = figure("tall", nrows=len(present), sharex=False)
    axes = np.atleast_1d(axes)
    duration = signal.size / fs

    for axis, name in zip(axes, present, strict=True):
        coefficients = bands[name]
        times = np.linspace(0.0, duration, coefficients.size, endpoint=False)
        axis.plot(times, coefficients, linewidth=0.5, color="#0072B2")
        # The band goes in the y-label rather than in an annotation inside the
        # panel: the first draft floated it over the trace, where it collided
        # with the waveform on every sub-band that actually has content.
        axis.set_ylabel(
            name + "\n" + _band_label(name, fs) + "\n" + str(coefficients.size) + " coef.",
            rotation=0,
            ha="right",
            va="center",
            fontsize=7,
        )
        axis.set_xlim(0.0, duration)
        axis.tick_params(labelbottom=False, labelsize=7)
        # Sub-band amplitudes span three orders of magnitude, so the default tick
        # locator crowds four labels into a panel 0.9 inches tall.
        axis.locator_params(axis="y", nbins=3)

    axes[-1].tick_params(labelbottom=True)
    axes[-1].set_xlabel("Time (s)")
    axes[0].set_title(
        str(settings.level)
        + "-level "
        + settings.wavelet
        + " decomposition, "
        + str(record["record_uid"])
    )
    fig.tight_layout()

    return save_figure(
        fig,
        path,
        source=(
            "FE-08 | "
            + str(record["record_uid"])
            + " | independent y-axes; only cD1 (500-1000 Hz) lies wholly outside "
            "the 20-400 Hz passband, and it carries a median 0.2% of decomposition "
            "energy across the corpus"
        ),
    )


def _band_label(name: str, fs: int) -> str:
    """The frequency range a named sub-band covers at this sampling rate."""
    nyquist = fs / 2.0
    if name.startswith("cD"):
        level = int(name[2:])
        low = format(nyquist / 2**level, ".4g")
        high = format(nyquist / 2 ** (level - 1), ".4g")
        return low + "-" + high + " Hz"
    level = int(name[2:])
    return "0-" + format(nyquist / 2**level, ".4g") + " Hz"


def plot_signal_envelope(path: str | Path, record: Any | None = None) -> Path:
    """FE-09 -- the preprocessed signal, its smoothed envelope and its peaks (T37.6).

    The detected peaks are drawn, not just the envelope, because ``env_peak_rate``
    is the one feature whose correctness a reader can check by eye: the markers
    should land on the S1/S2 bursts and nowhere else.
    """
    from src.feature_extraction.envelope import EnvelopeExtractor, envelope_peaks
    from src.reporting.plot_style import figure, save_figure

    if record is None:
        record = _representative()

    signal, fs = _preprocessed(record)
    extractor = EnvelopeExtractor()
    envelope = extractor.envelope_of(signal, fs)
    peaks = envelope_peaks(envelope, fs, extractor.settings())

    # A 17-second waveform at 2 kHz is 35,000 points of ink; the first six
    # seconds show the burst structure the envelope is tracking.
    window = min(signal.size, int(6.0 * fs))
    times = np.arange(window) / fs
    visible = peaks[peaks < window]

    fig, axis = figure("double")
    axis.plot(times, signal[:window], linewidth=0.4, color="#999999", label="Preprocessed signal")
    axis.plot(
        times,
        envelope[:window],
        linewidth=1.4,
        color="#D55E00",
        label="Hilbert envelope (20 Hz low-pass)",
    )
    axis.plot(
        visible / fs,
        envelope[visible],
        "v",
        color="#0072B2",
        markersize=6,
        linestyle="none",
        label="Detected peaks",
    )
    axis.set_xlim(0.0, times[-1] if times.size else 1.0)
    axis.set_xlabel("Time (s)")
    axis.set_ylabel("Amplitude (z-normalized)")
    rate = peaks.size / (signal.size / fs)
    axis.set_title(
        "Signal envelope and peak detection, "
        + str(record["record_uid"])
        + " (peak rate "
        + format(rate, ".2f")
        + " sounds/s)"
    )
    axis.legend(loc="upper right", fontsize=7)
    fig.tight_layout()

    return save_figure(
        fig,
        path,
        source=(
            "FE-09 | "
            + str(record["record_uid"])
            + " | first "
            + format(window / fs, ".0f")
            + " s of "
            + format(signal.size / fs, ".0f")
            + " s | env_peak_rate counts heart SOUNDS (S1 and S2), not beats -- "
            "never convert it to bpm by multiplying by 60 (T37.5)"
        ),
    )


def diagrams_dir(out_dir: str | Path | None = None) -> Path:
    from src.utils.config import load_config
    from src.utils.io import ensure_dir

    if out_dir is not None:
        return ensure_dir(out_dir)
    return ensure_dir(load_config("paths").require("outputs.figures_diagrams"))


def plot_mfcc_heatmap(path: str | Path, record: Any | None = None) -> Path:
    """FE-06 -- the 13 MFCCs over time for one representative record (T42.2).

    **c0 and c1 are drawn as lines, not as heatmap rows.** Their ranges do not
    overlap the rest: on the representative record c0 spans -63 to 49 (frame
    log-energy) and c1 spans 53 to 109 (overall spectral slope), while c2-c12
    together sit inside -16 to 42. Putting either into the same colour scale
    paints its row a saturated yellow and flattens every other coefficient into
    one uniform block -- arithmetically correct and completely unreadable. The
    first draft of this figure did exactly that.

    Dropping them instead would be worse: the extractor computes all 13 and the
    feature vector uses all 13, so a figure showing 11 would misrepresent what
    the family is. They are shown, on an axis where they are legible.
    """
    from src.feature_extraction.mfcc import MFCCExtractor, mfcc_matrix
    from src.reporting.plot_style import SEQUENTIAL_CMAP, figure, save_figure

    if record is None:
        record = _representative()

    signal, fs = _preprocessed(record)
    settings = MFCCExtractor().settings()
    mfcc = mfcc_matrix(signal, fs, settings)
    if mfcc.shape[1] == 0:
        raise ValueError(
            "MFCC matrix is empty for "
            + str(record["record_uid"])
            + "; cannot draw FE-06"
        )

    duration = signal.size / fs
    times = np.linspace(0.0, duration, mfcc.shape[1], endpoint=False)
    fig, axes = figure("tall", nrows=2, height_ratios=[1, 3])

    axes[0].plot(times, mfcc[0], linewidth=0.9, color="#D55E00", label="c0 (log-energy)")
    if mfcc.shape[0] > 1:
        axes[0].plot(
            times, mfcc[1], linewidth=0.9, color="#0072B2", label="c1 (spectral slope)"
        )
    axes[0].set_xlim(0.0, duration)
    axes[0].set_ylabel("Value", fontsize=7)
    axes[0].tick_params(labelbottom=False, labelsize=7)
    # Headroom for the legend: c1 runs flat across the top of its own range, so
    # an in-axes legend lands on the trace without it.
    low = float(min(mfcc[0].min(), mfcc[1].min() if mfcc.shape[0] > 1 else 0.0))
    high = float(max(mfcc[0].max(), mfcc[1].max() if mfcc.shape[0] > 1 else 0.0))
    axes[0].set_ylim(low - 0.05 * (high - low), high + 0.42 * (high - low))
    axes[0].legend(fontsize=6, loc="upper right", ncol=2, framealpha=0.9)
    axes[0].set_title(
        "MFCC representation, "
        + str(record["record_uid"])
        + " ("
        + str(settings.n_mfcc)
        + " coefficients, "
        + str(int(settings.fmin))
        + "-"
        + str(int(settings.fmax))
        + " Hz mel filterbank)"
    )

    rest = mfcc[2:]
    image = axes[1].imshow(
        rest,
        aspect="auto",
        origin="lower",
        cmap=SEQUENTIAL_CMAP,
        extent=(0.0, duration, 1.5, rest.shape[0] + 1.5),
    )
    axes[1].set_yticks(range(2, rest.shape[0] + 2))
    axes[1].set_xlabel("Time (s)")
    axes[1].set_ylabel("Coefficient index (c2 - c" + str(rest.shape[0] + 1) + ")")
    bar = fig.colorbar(image, ax=axes[1])
    bar.set_label("MFCC value")

    return save_figure(
        fig,
        path,
        source=(
            "FE-06 | "
            + str(record["record_uid"])
            + " | c0 ["
            + format(mfcc[0].min(), ".0f")
            + ", "
            + format(mfcc[0].max(), ".0f")
            + "] and c1 ["
            + format(mfcc[1].min(), ".0f")
            + ", "
            + format(mfcc[1].max(), ".0f")
            + "] are drawn as lines: their ranges do not overlap\nc2-c12 ["
            + format(rest.min(), ".0f")
            + ", "
            + format(rest.max(), ".0f")
            + "], and either one in the heatmap flattens the rest to a uniform block.\n"
            "Log-mel uses ref=1.0 and top_db=None -- librosa's default top_db=80 would\n"
            "normalize each record against its own maximum (T34.1)."
        ),
    )


def plot_family_counts(path: str | Path) -> Path:
    """G10 -- the 24/22/39/24/24/5 composition (T42.3).

    Counts come from the registry, never from a literal. The whole point of the
    figure is to show what the registry contains; a hand-typed 39 would make it
    a picture of what someone believed it contained.
    """
    from src.feature_extraction.registry import (
        EXPECTED_FAMILY_COUNTS,
        FAMILY_ORDER,
        FEATURE_NAMES,
        feature_names,
        registry_fingerprint,
    )
    from src.reporting.plot_style import class_color, figure, save_figure

    counts = [len(feature_names(family)) for family in FAMILY_ORDER]
    expected = [EXPECTED_FAMILY_COUNTS[family] for family in FAMILY_ORDER]
    if counts != expected:
        raise ValueError(
            "registry counts "
            + str(counts)
            + " do not match the locked composition "
            + str(expected)
            + "; G10 must not be drawn from a registry that disagrees with config"
        )

    total = len(FEATURE_NAMES)
    fig, axis = figure("double")
    positions = range(len(FAMILY_ORDER))
    bars = axis.bar(
        positions,
        counts,
        color=[class_color(index) for index in positions],
        edgecolor="black",
        linewidth=0.6,
    )
    for bar_patch, count in zip(bars, counts, strict=True):
        axis.text(
            bar_patch.get_x() + bar_patch.get_width() / 2.0,
            count + 0.6,
            str(count) + "\n" + format(100.0 * count / total, ".1f") + "%",
            ha="center",
            va="bottom",
            fontsize=7,
        )

    axis.set_xticks(list(positions))
    axis.set_xticklabels(list(FAMILY_ORDER))
    axis.set_ylabel("Features")
    axis.set_ylim(0, max(counts) * 1.28)
    axis.set_xlabel("Feature family")
    axis.set_title("Feature-family composition (" + str(total) + " features)")
    fig.tight_layout()

    return save_figure(
        fig,
        path,
        source=(
            "G10 | source: the feature registry (fingerprint "
            + registry_fingerprint()[:12]
            + ") | counts are read from the registry, never typed"
        ),
    )


def generate_all(out_dir: str | Path | None = None) -> dict[str, Path]:
    """Emit every feature figure built so far."""
    directory = features_dir(out_dir)
    record = _representative()
    return {
        "FE-06": plot_mfcc_heatmap(directory / FE_FIGURES["FE-06"], record),
        "FE-07": plot_chroma_heatmap(directory / FE_FIGURES["FE-07"], record),
        "FE-08": plot_wavelet_decomposition(directory / FE_FIGURES["FE-08"], record),
        "FE-09": plot_signal_envelope(directory / FE_FIGURES["FE-09"], record),
        # G10's home is outputs/13_figures_diagrams, but an explicit out_dir
        # (a test's tmp_path) must keep every figure inside it -- otherwise
        # calling generate_all in a test writes into the real outputs tree.
        "G10": plot_family_counts(
            (diagrams_dir() if out_dir is None else directory) / G10_FILENAME
        ),
    }
