"""Feature-family figures: FE-07 in Phase 35, FE-08 and FE-09 to follow.

**The record is chosen by rule, not by eye.** These figures reuse
:func:`src.preprocessing.figures.select_records`, which resolves "a
representative normal PhysioNet recording" to the labelled, non-duplicate,
non-low-quality D1 record whose duration is closest to its class median, with
``record_uid`` breaking ties. A figure captioned "representative" that was
actually picked because it looked good is a quiet form of cherry-picking and
cannot be regenerated by anyone checking the work.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

__all__ = ["FE_FIGURES", "features_dir", "plot_chroma_heatmap", "generate_all"]

FE_FIGURES: dict[str, str] = {
    "FE-07": "chroma_heatmap.png",
}


def features_dir(out_dir: str | Path | None = None) -> Path:
    from src.utils.config import load_config
    from src.utils.io import ensure_dir

    if out_dir is not None:
        return ensure_dir(out_dir)
    return ensure_dir(load_config("paths").require("outputs.features"))


def _representative() -> Any:
    from src.preprocessing.figures import select_records

    return select_records()["normal"]


def _preprocessed(record: Any) -> tuple[np.ndarray, int]:
    from src.preprocessing.pipeline import preprocess
    from src.utils.config import load_config

    root = Path(load_config("paths").require("project_root"))
    result = preprocess(root / str(record["file_path"]), record_uid=str(record["record_uid"]))
    return np.asarray(result.signal, dtype=np.float64), int(result.fs)


def plot_chroma_heatmap(
    path: str | Path, record: Any | None = None
) -> Path:
    """FE-07 -- the 12 chroma bins over time for one representative record (T35.6).

    The caption carries the T35.4 caveat, because a chroma heatmap of a heart
    sound invites exactly the musical reading the family does not support.
    """
    from src.feature_extraction.chroma import ChromaExtractor, chroma_matrix
    from src.reporting.plot_style import figure, save_figure

    if record is None:
        record = _representative()

    signal, fs = _preprocessed(record)
    settings = ChromaExtractor().settings()
    chroma = chroma_matrix(signal, fs, settings)
    if chroma.shape[1] == 0:
        raise ValueError(
            "chroma is empty for " + str(record["record_uid"]) + "; cannot draw FE-07"
        )

    duration = signal.size / fs
    low = float(chroma.min())
    high = float(chroma.max())

    # The colour scale spans the data, not a nominal 0-1. `chroma_stft`
    # normalizes every frame by its maximum, and a PCG spreads energy almost
    # evenly across the twelve pitch classes, so the real range on this corpus is
    # roughly 0.5-1.0. Forcing vmin=0 produced a uniformly bright rectangle:
    # arithmetically correct and completely unreadable. The caption states the
    # true range so the narrow dynamic range stays visible rather than being
    # hidden by the stretch -- that flatness is itself the T35.4 point.
    fig, axis = figure("double")
    image = axis.imshow(
        chroma,
        aspect="auto",
        origin="lower",
        cmap="magma",
        vmin=low,
        vmax=high,
        extent=(0.0, duration, 0.5, settings.n_chroma + 0.5),
    )
    axis.set_yticks(range(1, settings.n_chroma + 1))
    axis.set_xlabel("Time (s)")
    axis.set_ylabel("Chroma bin")
    axis.set_title(
        "Chroma representation, "
        + str(record["record_uid"])
        + " ("
        + str(settings.n_chroma)
        + " bins, "
        + str(int(settings.fmin))
        + "-"
        + str(int(settings.fmax))
        + " Hz)"
    )
    bar = fig.colorbar(image, ax=axis)
    bar.set_label("Normalized chroma energy")
    fig.tight_layout()

    return save_figure(
        fig,
        path,
        source=(
            "FE-07 | "
            + str(record["record_uid"])
            + " | range "
            + format(low, ".3f")
            + "-"
            + format(high, ".3f")
            + " | chroma is a musical-pitch construct with no physiological meaning "
            "for heart sounds; used here only as a generic harmonic-distribution "
            "descriptor (T35.4)"
        ),
    )


def generate_all(out_dir: str | Path | None = None) -> dict[str, Path]:
    """Emit every feature figure built so far."""
    directory = features_dir(out_dir)
    record = _representative()
    return {"FE-07": plot_chroma_heatmap(directory / FE_FIGURES["FE-07"], record)}
